---
# Source: helm for kubernetes/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "test-gradle-mi-knath-2"
  namespace: "argocd"
spec:
  project: default
  source:
    repoURL: https://github.com/BunathPheng/test-gradle-mi-knath-2-manifests.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: smartops-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
eNamespace=true
