---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-gradle
  labels:
    app: test-gradle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gradle
  template:
    metadata:
      labels:
        app: test-gradle
    spec:
      containers:
        - name: test-gradle
          image: docker.io/phengbunath/test-gradle:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          ports:
            - containerPort: 8080
Always
          ports:
            - containerPort: 8080
