---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-gradle-mi-knath
  labels:
    app: test-gradle-mi-knath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gradle-mi-knath
  template:
    metadata:
      labels:
        app: test-gradle-mi-knath
    spec:
      containers:
        - name: test-gradle-mi-knath
          image: docker.io/phengbunath/test-gradle-mi-knath:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
Always
          ports:
            - containerPort: 8080
