---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-gradle-mi-knath                  # Ingress name
  labels:
    app: test-gradle-mi-knath
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "test-gradle-mi-knath.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-gradle-mi-knath               # Links to Service name dynamically
                port:
                  number: 8080  # Links to service port dynamically
